### ISSUE TITLE
 logi_score is NaN

### ISSUE THREAD

**Issue by FantasticGNU** [Tokichan/CSAD#1]
While running train_segmentor.py, the logi_score sometimes becomes NaN and then the training breaks.

**Comment by FantasticGNU** [comment]
The problem lies in line 75 of the normalize() function in models/segmentation/patch_histogram.py. The val_score may be all 0, and at this time, score = score/np.std(val_score) will produce NaN.

**Comment by Tokichan** [comment]
This problem should be fixed in the newest update.
